# https://starship.rs/ja-jp/config/

# 空行追加
add_newline = true

# タイムアウト時間
scan_timeout = 10
command_timeout = 800

# プロンプト
[hostname]
ssh_only = true

[username]
show_always = false

[package]
disabled = true

[aws]
disabled = true

[azure]
disabled = true

[gcloud]
disabled = true

[directory]
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"
style = "white"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "purple"

[git_status]
style = "purple"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

[time]
disabled = false
format = "[$time]($style) "
style = "bold dimmed cyan"
